version: '3'
services:
  streaming:
    image: hyunsalex/streaming:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streaming
    ports:
      - "4000:80"
    environment:
      - PORT=80
    restart: "no"