version: '3'
services:
  s3storage:
    image: s3storage:latest
    build:
      context: ./s3storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - AWS_ACCESS_KEY_ID=accesskey
      - AWS_SECRET_ACCESS_KEY=secretkey
    restart: no
  
  video-streaming:
    image: video-streaming:latest
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: no